spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false
  sql:
    init:
      mode: always
      schema-locations: schema.sql

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false
  #data:
  #  mongodb:
  #    #port: 0 # when flapdoodle using
  #    #database: company
  #    authentication-database: admin
  #    username: myUserAdmin
  #    password: Qq123456
  #    database: user_db
  #    port: 27017
  #    host: localhost


  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123

  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
