spring:
  http:
    encoding:
      charset: UTF-8
    enabled: true
  h2:
    console:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: Qq123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true