management:
  server:
    port: 8085
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  export:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Qq123456
    key-store-type: pkcs12
    key-alias: 1
    key-password: Qq123456
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: UTF-8
    enabled: true
  h2:
    console:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: Qq123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true